### ISSUE TITLE
Workflow to Update Other Repos

### ISSUE THREAD

**Issue by AjayAujla** [AjayAujla/Portfolio#13]
Squash and force push to:
- https://github.com/AjayAujla/ajayaujla.com
- https://github.com/AjayAujla/ajayaujla.github.io

References
- https://help.github.com/en/actions/getting-started-with-github-actions/using-actions-from-github-marketplace
- https://github.com/AjayAujla/Portfolio/edit/master/.github/workflows/main.yml
- https://github.com/actions/checkout#checkout-multiple-repos-private
- https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
- https://github.com/marketplace/actions/push-directory-to-another-repository
- https://github.com/marketplace/actions/git-sync-action
- https://github.com/marketplace/actions/github-repo-sync

**Comment by AjayAujla** [comment]
```
name: Update Other Repos
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: |
          git clone https://github.com/AjayAujla/ajayaujla.com
          cd ajayaujla.com
          
```
